202308140107
plz-input-name/MCheap pull request #14
Opened 2023-08-13 16:09 UTC by YangJJune

- 메인에 최근 검색어 10개 불러오는 기능 추가
- 플로팅 버튼 추가
- 버그 제거

etc...

2023-08-13 22:33 UTC, Roysung0625 approved these changes

2023-08-15 07:01 UTC, Roysung0625 approved these changes

2023-08-15 10:46 UTC, Roysung0625 approved these changes

2023-08-15 11:06 UTC, goldentrash approved these changes

2023-08-15 11:07 UTC, goldentrash commented
main의 변경점이 제대로 rebase가 안 된 거 같은데

2023-08-15 11:07 UTC, goldentrash requested changes
main rebase 재확인 요망

2023-08-16 10:23 UTC, closed without merging

2023-08-16 10:24 UTC, goldentrash commented
github rebase 후, local branch 미삭제로 대규모 충돌 발생